#!/bin/bash

sudo ~/dpdk/tools/dpdk_nic_bind.py -u 0000:08:00.0
sudo ~/dpdk/tools/dpdk_nic_bind.py -u 0000:08:00.1

sudo rmmod rte_kni
sudo rmmod igb_uio
sudo rmmod uio

sudo rmmod ixgbe
sudo modprobe ixgbe

sudo ifconfig p2p1 192.168.18.2
sudo ifconfig p2p2 192.168.19.2
